const employees = [
  {
    id: 1,
    firstname: "Aarav",
    email: "employee1@example.com",
    password: "1234",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Prepare Monthly Sales Report",
        description: "Compile and analyze sales data for the month.",
        date: "2025-08-16",
        category: "Reporting",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Client Follow-up Emails",
        description: "Send follow-up emails to potential leads.",
        date: "2025-08-14",
        category: "Communication",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Update Product Listings",
        description: "Refresh product descriptions and images on the website.",
        date: "2025-08-12",
        category: "E-commerce",
      },
    ],
    taskStats: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 2,
    firstname: "Ishita",
    email: "employee2@example.com",
    password: "1234",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Design Landing Page",
        description: "Create wireframe and design assets for new landing page.",
        date: "2025-08-18",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Fix UI Bugs",
        description: "Resolve reported UI/UX issues from testing.",
        date: "2025-08-15",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Write Blog Post",
        description: "Draft blog post for company newsletter.",
        date: "2025-08-13",
        category: "Content",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Prepare Marketing Strategy",
        description: "Outline next quarter's marketing approach.",
        date: "2025-08-20",
        category: "Marketing",
      },
    ],
    taskStats: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 3,
    firstname: "Kabir",
    email: "employee3@example.com",
    password: "1234",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Database Backup",
        description: "Perform full database backup and store securely.",
        date: "2025-08-16",
        category: "IT",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Security Audit",
        description: "Run security scans and patch vulnerabilities.",
        date: "2025-08-15",
        category: "Security",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        title: "Optimize Queries",
        description: "Improve database performance by optimizing queries.",
        date: "2025-08-17",
        category: "Database",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Data Migration",
        description: "Move legacy data to the new system.",
        date: "2025-08-12",
        category: "Database",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Server Monitoring Setup",
        description: "Implement server monitoring tools for uptime tracking.",
        date: "2025-08-19",
        category: "IT",
      },
    ],
    taskStats: {
      active: 2,
      newTask: 2,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 4,
    firstname: "Meera",
    email: "employee4@example.com",
    password: "1234",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Customer Feedback Survey",
        description: "Design and distribute customer satisfaction survey.",
        date: "2025-08-16",
        category: "Customer Service",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Update FAQ Section",
        description: "Revise the FAQ section on the website.",
        date: "2025-08-14",
        category: "Content",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Train New Interns",
        description: "Provide onboarding and training to interns.",
        date: "2025-08-13",
        category: "Training",
      },
    ],
    taskStats: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 5,
    firstname: "Rohan",
    email: "employee5@example.com",
    password: "1234",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Test Payment Gateway",
        description: "Ensure all payment methods are functioning correctly.",
        date: "2025-08-16",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "API Documentation",
        description: "Document all API endpoints with examples.",
        date: "2025-08-14",
        category: "Development",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        title: "Refactor Codebase",
        description: "Improve maintainability by refactoring outdated code.",
        date: "2025-08-17",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Deploy to Production",
        description: "Push latest build to the production environment.",
        date: "2025-08-12",
        category: "Deployment",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Implement Dark Mode",
        description: "Add dark mode feature to the application UI.",
        date: "2025-08-19",
        category: "UI/UX",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Run Load Testing",
        description: "Test system performance under heavy load.",
        date: "2025-08-20",
        category: "Testing",
      },
    ],
    taskStats: {
      active: 3,
      newTask: 2,
      completed: 1,
      failed: 1,
    },
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "1234",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

//  JSON.parse = make data in array form instead of string form

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
